### ISSUE TITLE
【bug】设备管理器-》显示设备-》当前分辨率显示错误

### ISSUE THREAD

**Issue by widon1104** [linuxdeepin/deepin-devicemanager#6]
如图，当前分辨率明明是2k，但是设备管理器居然说我的分辨率是1080p
![截图录屏_选择区域_20210306194900](https://user-images.githubusercontent.com/12093211/110205930-e15bc400-7eb5-11eb-8239-c32029fa7fd3.jpg)

**Comment by UOS-Python** [comment]
> 如图，当前分辨率明明是2k，但是设备管理器居然说我的分辨率是1080p
> ![截图录屏_选择区域_20210306194900](https://user-images.githubusercontent.com/12093211/110205930-e15bc400-7eb5-11eb-8239-c32029fa7fd3.jpg)

你好，版本号可否提供下

**Comment by widon1104** [comment]
deepinV20.2.3下，这个问题已经修复了

**Comment by UOS-Python** [comment]
收到，多谢您的关注，也欢迎您继续提出问题，我们会持续关注
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Mon, Sep 13, 2021 05:36 PM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [linuxdeepin/deepin-devicemanager] 【bug】设备管理器-》显示设备-》当前分辨率显示错误 (#6)

&nbsp;



 
deepinV20.2.3下，这个问题已经修复了
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
